name: BossPersonalizados
version: '1.0.0'
main: com.darkmortol.bosspersonalizados.BossPersonalizadosPlugin
api-version: '1.21'
author: DARKMORTOL
description: Crea bosses personalizados con habilidades, armadura, encantamientos, respawn y radios de aparicion.

commands:
  boss:
    description: Comando principal de BossPersonalizados
    usage: /boss <crear|lista|editar|eliminar|eliminarpunto|huevo|cancelar>
    permission: bosspersonalizados.admin

softdepend: [Vault]

permissions:
  bosspersonalizados.admin:
    description: Permite crear, editar y eliminar bosses personalizados
    default: op
